[tool.poetry]
name = "hw3"
version = "0.1.0"
description = ""
authors = ["Aleksandr Tretyakov <aleksandr.tret.4@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
numpy = "^2.4.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
